### ISSUE TITLE
rsync's exit value is lost

### ISSUE THREAD

**Issue by harridu** [rsnapshot/rsnapshot#102]
Seems that rsnapshot looses rsync's exit value, e.g. if the remote host is unreachable. Sample debug output (verbose 5):
<pre>
:
/usr/bin/rsync -SHavx --delete --numeric-ids --relative --delete-excluded \
--exclude=Cache --exclude=tmp --rsh=/usr/bin/ssh \
--link-dest=/export/rsnapshot/alpha.1/daffy/ root@daffy:/ \
/export/rsnapshot/alpha.0/daffy/
ssh: connect to host daffy port 22: No route to host
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
rsync succeeded
:
</pre>
The old rsnapshot 1.3.1 used to do
<pre>
:
/usr/bin/rsync -SHavx --delete --numeric-ids --relative --delete-excluded \
--exclude=Cache --exclude=tmp --rsh=/usr/bin/ssh \
--link-dest=/export/rsnapshot/hourly.1/daffy/ root@daffy:/ \
/export/rsnapshot/hourly.0/daffy/
ssh: connect to host daffy port 22: No route to host
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
----------------------------------------------------------------------------
rsnapshot encountered an error! The program was invoked with these options:
/usr/bin/rsnapshot hourly 
----------------------------------------------------------------------------
ERROR: /usr/bin/rsync returned 255 while processing root@daffy:/
:
</pre>
This breaks rollback.

**Comment by bebehei** [comment]
Thanks for the report. I can confirm it. Probably this is inteded by feature #65

**Comment by xezpeleta** [comment]
Same problem here!

**Comment by harridu** [comment]
I doubt that this is in on purpose. $? just doesn't work with open3. The exit value of the child has to be processed using waitpid(2) and the usual test macros.

**Comment by bebehei** [comment]
Ok, I had to test waitpid's behavior. But now, in #103 is the fix. Could you please test it? I'd release a 1.4.1 tomorrow.

```
export pref=<your prefix>
git clone https://github.com/rsnapshot/rsnapshot.git
cd rsnapshot
git checkout 318b7d3feb44133fa3f0b30fecad3d0df3124416
./autogen.sh
./configure.sh --prefix=$pref
make
make test
make install
```

And then, just the normal game. Thanks.

**Comment by xezpeleta** [comment]
Thanks @bebehei , I tested the PR #103 and it seems to fix this issue.

**Comment by bebehei** [comment]
Thanks, will merge this now.

**Comment by vext01** [comment]
FWIW, I have something similar. I was using a DSA ssh key, which OpenSSH now rejects by default. When I updated OpenSSH rsnapshot's SSH connection was failing, but rsnapshot was not detecting this. In turn this lead to empty `daily.0` and `weekly.0` directories. I did not notice for some time, as the failure was silent. If I crank up the verbosity I see:

```
...
/usr/local/bin/rsync -av --delete --numeric-ids --relative ... 
Permission denied (publickey,keyboard-interactive).
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: unexplained error (code 255) at io.c(226) [Receiver=3.1.1]
...
rsnapshot.conf daily: completed successfully 
```

Looks like this is fixed now though?

**Comment by Jo-Con-El** [comment]
It is not fixed, at least for some cases.  For example, if rsync returns code 23 (error syncing some or all files) rsnapshot ignores that and just logs it.  In my case the destination directory doesn't exist at all and I haven't found it until many days later.  I'm following up with a couple of pull requests to try and fix it.

**Comment by sam-at-github** [comment]
Fixed in master. Closing.
